#!/usr/bin/env python3
"""
Cli for klea_rag.

File: klea_rag/ui/cli.py

Copyright 2026 Ankur Sinha
Author: Ankur Sinha <sanjay DOT ankur AT gmail DOT com>
"""

import asyncio
import subprocess
import uuid
from contextlib import chdir
from pathlib import Path

import httpx
import typer
from klea_utils.api import check_api_is_ready

rag_app = typer.Typer()


@rag_app.command()
def rag_cli(
    gui: bool = False,
    single_query: str = "",
):
    """Klea RAG cli client"""
    print("*** Klea AI chat assistant ***")
    print("Please note that answers are generated by LLMs and may be incorrect.")
    print()
    print("Type 'quit' to exit.")
    print()
    print()

    url = "http://127.0.0.1:8005"

    if not gui:

        async def cli_main():
            """Cli main async"""
            from yaspin import yaspin

            session_id = str(uuid.uuid4())

            with yaspin(text="Waiting for API..."):
                response = await check_api_is_ready(f"{url}/health/ready")

            if len(single_query):
                print(f"Klea-RAG (USER) >>> {single_query}\n\n")
                if single_query.lower() == "quit":
                    pass
                else:
                    with yaspin(text="Working ..."):
                        async with httpx.AsyncClient() as client:
                            response = await client.post(
                                f"{url}/query",
                                json={"query": single_query, "session_id": session_id},
                                timeout=None,
                            )
                            response_result = response.json().get("result")
                            print(f"Klea-RAG (AI) >>> {response_result}\n\n")

            else:
                while (query := input("Klea-RAG (USER) >>> ")) != "quit":
                    # we use checkpoints, so we don't need to store and reload the
                    # state ourselves
                    with yaspin(text="Working ..."):
                        async with httpx.AsyncClient() as client:
                            response = await client.post(
                                f"{url}/query",
                                json={"query": query, "session_id": session_id},
                                timeout=None,
                            )
                            response_result = response.json().get("result")
                            print(f"Klea-RAG (AI) >>> {response_result}\n\n")

        try:
            asyncio.run(cli_main())
        except KeyboardInterrupt:
            print("\nInterrupted. Exiting.")

    else:
        # streamlit app
        cwd = Path(__file__).parent
        with chdir(cwd):
            subprocess.run("streamlit run streamlit_ui.py".split())

    print("Klea-RAG >>> Bye!")


if __name__ == "__main__":
    rag_app()
